# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecacheSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('datetime', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
